3400320441 stg portal andrew
alewinskylyka/dbt-lyka pull request #9
Opened 2022-10-20 03:40 UTC by alewinskylyka

2022-10-20 03:51 UTC, lukersmithoscar requested changes

2022-10-20 03:51 UTC, lukersmithoscar commented on models/staging/portal/portal_source.yml
> +# Why do we need this file as well as portal_dat. Seems to be overkill?
Can you please remove this comment as we have discussed.

2022-10-20 03:55 UTC, alewinskylyka commented on models/staging/portal/portal_source.yml
> +# Why do we need this file as well as portal_dat. Seems to be overkill?
I have now removed the comment.

2022-10-20 03:56 UTC, lukersmithoscar approved these changes

2022-10-21 00:29 UTC, agpmercado commented
Merge for customer.io migration

2022-10-21 00:30 UTC, merged